### ISSUE TITLE
starknet_estimateFee failing

### ISSUE THREAD

**Issue by habbas33** [NethermindEth/juno#1186]
I am trying to call starknet_estimateFee to juno goerli node using postman. My request fails and shows error as below.

### My Request

```
{
  "method": "starknet_estimateFee",
  "jsonrpc": "2.0",
  "id": 1,
  "params": {
    "request": [
      {
        "type": "INVOKE",
        "nonce": "0x4",
        "max_fee": "0xde0b6b3a7640000",
        "sender_address": "0x021183387a5f40165c03fa88b447d78985419ab55e9d7d476dfeabc90c652a16",
        "calldata": [
          "0x1",
          "0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7",
          "0x83afd3f4caedc6eebf44246fe54e38c95e3179a5ec9ea81740eca5b482d12e",
          "0x0",
          "0x3",
          "0x3",
          "0x7eb30225565dc6c3111268475acd135d6031767975f82af47c7fdbe5fb9dca",
          "0x2540be400",
          "0x0"
        ],
        "version": "0x100000000000000000000000000000001",
        "signature": [
          "0x6ec6"
        ]
      }
    ],
    "block_id": "latest"
  }
}
```

### Error
`failed txn TransactionHash(StarkFelt(\"0x01258a361c98d3d49808ed9bfc41e4c7111e3521dd36200735d4c9b08b65b76e\")) reason:ValidateTransactionError(VirtualMachineExecutionErrorWithTrace { trace: \"Error in the called contract (0x021183387a5f40165c03fa88b447d78985419ab55e9d7d476dfeabc90c652a16):\\nError at pc=0:12:\\nGot an exception while executing a hint: Hint Error: Error in the called contract (0x021183387a5f40165c03fa88b447d78985419ab55e9d7d476dfeabc90c652a16):\\nError at pc=0:23:\\nGot an exception while executing a hint: Assertion failed, 0 <= ids.a % PRIME < range_check_builtin.bound \\n a = 3618502788666131213697322783095070105623107215331596699973092056135872020480 is out of range\\nCairo traceback (most recent call last):\\nUnknown location (pc=0:1323)\\nUnknown location (pc=0:1274)\\nError message: argent: signer signature invalid\\nUnknown location (pc=0:1044)\\n\\nCairo traceback (most recent call last):\\nUnknown location (pc=0:161)\\nUnknown location (pc=0:147)\\n\\nError in the called contract (0x021183387a5f40165c03fa88b447d78985419ab55e9d7d476dfeabc90c652a16):\\nError at pc=0:23:\\nGot an exception while executing a hint: Assertion failed, 0 <= ids.a % PRIME < range_check_builtin.bound \\n a = 3618502788666131213697322783095070105623107215331596699973092056135872020480 is out of range\\nCairo traceback (most recent call last):\\nUnknown location (pc=0:1323)\\nUnknown location (pc=0:1274)\\nError message: argent: signer signature invalid\\nUnknown location (pc=0:1044)\\n\", source: CairoRunError(VmException(VmException { pc: 12, inst_location: None, inner_exc: Hint((0, CustomHint(\"Error in the called contract (0x021183387a5f40165c03fa88b447d78985419ab55e9d7d476dfeabc90c652a16):\\nError at pc=0:23:\\nGot an exception while executing a hint: Assertion failed, 0 <= ids.a % PRIME < range_check_builtin.bound \\n a = 3618502788666131213697322783095070105623107215331596699973092056135872020480 is out of range\\nCairo traceback (most recent call last):\\nUnknown location (pc=0:1323)\\nUnknown location (pc=0:1274)\\nError message: argent: signer signature invalid\\nUnknown location (pc=0:1044)\\n\"))), error_attr_value: None, traceback: Some(\"Cairo traceback (most recent call last):\\nUnknown location (pc=0:161)\\nUnknown location (pc=0:147)\\n\") })) })"`

## 2
I also tried using [starknetjs](https://www.starknetjs.com/docs/guides/connect_network) to estimatefee which works for alchemy rpc url but fails for juno 

### js script 
```
const starknet = require("starknet")
const { TO_ADDRESS_SN_TESTNET, FROM_ADDRESS_SN_TESTNET, L2_FEE_CONTRACT_ADDRESS } = require('./constants/globals')
require("dotenv").config()

const provider = new starknet.Provider({ rpc: { nodeUrl: `http://18.188.88.200:6060/` } })
// const provider = new starknet.Provider({ rpc: { nodeUrl: process.env.ALCHEMY_KEY_GOERLI_RPC_URL } })

// load starknet account
const useStarkNetAccount = () =>{
  const account = new starknet.Account(
      provider,
      FROM_ADDRESS_SN_TESTNET.toLowerCase(),
      process.env.SN_PVT_KEY_TESTNET
  );
  return account
}

// estimate eth transfer fee in L2
const estimateEthTransferFee = async (account) =>{
  const res = await account.estimateInvokeFee(
      {
          contractAddress: L2_FEE_CONTRACT_ADDRESS.toLowerCase(),
          entrypoint: "transfer",
          calldata: [
              TO_ADDRESS_SN_TESTNET.toLowerCase(),
              "10000000000",
              "0"
            ]
      });
  return res.overall_fee
}

const collectFeeEstimate = async () => {
  const account = useStarkNetAccount()
  
  try {
    const lastBlock = await provider.getBlock("latest")
    console.log(lastBlock) //this works

    const ethTransferFee = await estimateEthTransferFee(account)
    console.log(ethTransferFee) //doesnt work

    return 1
  } catch (error) {
    console.log("Error: Fee estimate calls failed for ", error)
    return 0
  }
}

collectFeeEstimate()
```

**Comment by IronGauntlets** [comment]
Which network are you using?

**Comment by wojciechos** [comment]
> My Request

I guess that the root of the issue might be in the validity of your request. I tested a similar request with Infura and get similar error, suggesting that the txn you're trying to estimate is invalid.

> js script

Could you provide more detailed error messages or logs? I've just run your code with Juno as rpc and was able to retrieve the `ethTransferFee` successfully.

**Comment by habbas33** [comment]
> >Could you provide more detailed error messages or logs? I've just run your code with Juno as rpc and was able to retrieve the `ethTransferFee` successfully.

I tried some more
using Argent testnet account I got this result 
**With juno Goerli RPC**
```
{
  overall_fee: 0n,
  gas_consumed: 0n,
  gas_price: 1000000013n,
  suggestedMaxFee: 0n
}
```
**With Alchemy**
```
{
  overall_fee: 3753000048789n,
  gas_consumed: 3753n,
  gas_price: 1000000013n,
  suggestedMaxFee: 5629500073183n
}
```
I again tried with newly created Bravos Goerli Account
**With Alchemy**
```
{
  overall_fee: 3764000052696n,
  gas_consumed: 3764n,
  gas_price: 1000000014n,
  suggestedMaxFee: 5646000079044n
}
```
**With juno Goerli RPC**
```
Error: failed for  LibraryError: 40: Contract error
    at RpcProvider.errorHandler (/Users/haider/Work/Voyager/test/node_modules/starknet/dist/index.js:4077:13)
    at RpcProvider.fetchEndpoint (/Users/haider/Work/Voyager/test/node_modules/starknet/dist/index.js:4084:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Account.estimateInvokeFee (/Users/haider/Work/Voyager/test/node_modules/starknet/dist/index.js:5612:22)
```

May I ask which starknetjs version you used? I am using ^5.14.1

**Comment by wojciechos** [comment]
Thank you for the detailed information.
Like you, I'm using starknet@5.14.1 and also the Bravos Goerli Account. Which version of Juno are you using?

Here is my output from your code:
```C:\sources\starknet-js-playground> node .\playground.js
{
  timestamp: 1693474357,
  block_hash: '0x194e9118192a6dc538129b2b44741331ff97b8fcec152266613f38710aba396',
  block_number: 854360,
  new_root: '0xa2d402e16c520326c05be160f4f4b638c897ddfa38809015b7fed2100507c4',
  parent_hash: '0x4aff3613d2cc7e95f2d3ec30162f41820934b2ec8461491a9202416488ddb63',
  status: 'ACCEPTED_ON_L2',
  transactions: [
    '0x784ec70af4c3f8a64455d44432394596dc47ce0e005560203a1799604462447',
    '0x2ac1d5b0794e74b306ca38fba592669412667cfc6d68a5c6a3897111cfd1aaa',
    '0x5204dd84bdc140ff9ecdf2ebb387b83b131b80261cfe5e4d7c335013a44b709',
    '0x65063bc4f043df9ccee738a03db9667059e05362208be3e94e36c49525f862f',
    '0x8b86f00be162a50998c3704d6bfd2550efc79f4a9382e588378dc6d256c3a5',
    '0x375ec33ea09866050de4b2a2940011a053be482de2807977132e81dae4a00f8',
    '0x4ed1d4e184b18d7f12da8ae3bd27c6eda9e9277b433fd935167d4381b5a2329',
    '0x49cb9c5d9fd6ebe7bf129c80d909652f07e1657b5d2eef83a9a7569aa84ac4b',
    '0x7b05650504b9331cac75a752c0ae569e0e4d5930b1de91903c5a61902c7b85b',
    '0x68d72927907a856ddbbbbc5acaf8932af9b84940e339c36dfab13bf0c0122a',
    '0x5c509e253ce59b394044a68d85b58cdd1077a08a86f80ad63cd3fa4715812f6',
    '0x4ad1e6f327bd4132a0597132029af95f3731b4276abf2abfe360b4863f4a3e3',
    '0x2048dc357dfbd638454e524caab32d8244f78796110321e2e53220417f828d8',
    '0x36cdc291402c5fcf847e538786efb4cb4d65362308569ee530bd0a19edfd869',
    '0x3b4965b30c7dbb103d1ce49cb44ec6d2af8d6d913abbfb4fbc69492ecb41b2c',
    '0x3d5c1df21e7c5517972ef43d6c28027620e340e79be51c649ced0d198852ab2',
    '0x64f404fbdaa8403e9ec41683bf9ee7492ad559ef8b3351df0582898158669f6',
    '0x5389859dcb60e2b621a05822791380b6cd6d8ed63ff645bfa4b5b427057fcb0',
    '0x116dd4ca14d2a010f8416b35e8ac666f80cf13a2b8a218c6575dadec10195fe',
    '0x51dee3799f1f9533c0089ee2130485f2c2b8c6d4994bc7c6d573b4be462916f',
    '0x787d0fd7e9e6944ab8a1eb123bf3f8fc6b7ab456ddffd7d1b1015b201f39312',
    '0x103c08b6e4e33a892dd08936f499c5b19fc147a66658462e53f6f475e39fa62',
    '0x23018dd4ee981c924449cf7cd94aea6a4e71118c230ef1db036f60561540fab',
    '0x3fd26a64bccad7dac4aa26305816d2a105cba8c2f7b9e59c6bb180ccd0e940b',
    '0x1f9a2f2a2e0d1905144b1d4162bd2960f61aaceaae1a5281eb008d50798577f',
    '0x31573010628c025325f25674310b9e1ce670c0713a9e9d4df539a9890b14a4b',
    '0x4ec5620ba7d0c5eb6e50824d0556e3eba283eb9d8c12e8a14f2af90c9ddf681',
    '0x46a54bac8528e5960e28784dc418b965331d2df30dae3bc23409d97ccd6c946',
    '0x1d50902b2748faf540cf8f7efc0420439f8282d388785fcf1da0a21fae78be6',
    '0x7603b9b7efac2e52b38a5ea9eac10082787340e81474e252374e0f24731e4bc',
    '0x6b000ac103db5a6fe2c86e154b897ee0163e56163b9fa813f70a9cfd008a23e',
    '0x93c551fd2b1332cb2abf7a596f1fd077b3d3d4a35337b2a8670887d271cc76',
    '0x2e83162d597f6a59b2a06118974b9a5d8c755a6e72a78d26958a8d515e933d2',
    '0x1150ce29a251fc479c73cc5d8284b86c45ae4c3a48a6dfff04dd2b2a1ec49ad',
    '0x5c0ba79d92a906f18ca05e3a0fc554d51a901e50a41182b59e46ccae3d0e067',
    '0x55c9722b753f5cdffa6da0f717d46f8075ef62e986fc9b083ce125bcf98e6d5',
    '0x327d2c8e55a6f7d652de7b2d646bcefd4e08b5f7133a28718b5c261403447d6',
    '0x64dc637b35db78536638d980496e94d2359baed8369e2662bbe0dd64b64c648',
    '0x28cbb627c6777f58e7112124ee46e4cc8e8786c4238a7497ee8f502b312ffca'
  ]
}
2533002305030n
PS C:\sources\starknet-js-playground> npm list starknet
starknet-js-playground@1.0.0 C:\sources\starknet-js-playground
`-- starknet@5.14.1
```

Here is sample request generated via starknet-js:
```
{
    "method": "starknet_estimateFee",
    "jsonrpc": "2.0",
    "params": {
        "request": [
            {
                "type": "INVOKE",
                "sender_address": "0x006863c65c645c4ed60a2c170891219b537697a6f576afc7237d47cf05ce1032",
                "calldata": [
                    "0x1",
                    "0x7eb30225565dc6c3111268475acd135d6031767975f82af47c7fdbe5fb9dca",
                    "0x83afd3f4caedc6eebf44246fe54e38c95e3179a5ec9ea81740eca5b482d12e",
                    "0x0",
                    "0x3",
                    "0x3",
                    "0x5d005568fea08974879af89ade56c9817c71a3f1bc0d8397d16f3869ea797df",
                    "0x2540be400",
                    "0x0"
                ],
                "version": "0x100000000000000000000000000000001",
                "signature": [
                    "0x5e34296631464c82d8651c673faf577a5f00968aca6b84b564a78c2dae95823",
                    "0x3a0287a105d613152d2343f39246e1b340a2bf261cbd48c455576a63fbaa674"
                ],
                "nonce": "0x5",
                "max_fee": "0x0"
            }
        ],
        "block_id": "latest"
    },
    "id": 0
}
```
Results:
```
{
    "jsonrpc": "2.0",
    "result": [
        {
            "gas_consumed": "0x9e5",
            "gas_price": "0x3b9ad032",
            "overall_fee": "0x24dc2cdfeba"
        }
    ],
    "id": 0
}
```

Can you check if this request works for your node?

**Comment by wojciechos** [comment]
@habbas33 I just checked and your node(http://18.188.88.200:6060) is v0.5.1. Please upgrade your node to [v0.6.0](https://github.com/NethermindEth/juno/releases/tag/v0.6.0) and all should be fine! :)

**Comment by habbas33** [comment]
oh Great thanks alot
